<?php

namespace test;

use wiro\helpers\App;
use wiro\helpers\Yii;
use wiro\test\TestCase;

/**
 * Test class for WebApplication.
 * Generated by PHPUnit on 2013-04-11 at 13:01:07.
 */
class WebApplicationTest extends TestCase
{
    public $mockComponents = array('request');
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
	parent::setUp();
        App::request()->shouldReceive('getHostInfo')->andReturn('http://somehost.com');
	App::setRootPath(null);
	App::setRootUrl(null);
	Yii::alias('root', '/some/rootpath');
	$_SERVER['DOCUMENT_ROOT'] = '/just/some/';
    }

    /**
     * @covers wiro\base\WebApplication::getRootUrl
     * @todo Implement testGetRootUrl().
     */
    public function testGetRootPath()
    {
	$this->assertEquals(Yii::pathOf('@root'), App::rootPath());
	
	App::rootPath('/some/other/dir');
	$this->assertEquals('/some/other/dir', App::rootPath());
	
	App::rootPath('/some/other/dir/');
	$this->assertEquals('/some/other/dir', App::rootPath());
    }

    /**
     * @covers wiro\base\WebApplication::setRootUrl
     * @todo Implement testSetRootUrl().
     */
    public function testGetRootUrl()
    {
	App::rootPath('/some/other/dir');
	$this->assertEquals('/dir', App::rootUrl());
	
	App::rootUrl('/somedir');
	$this->assertEquals('/somedir', App::rootUrl());
	
	App::rootUrl('/somedir/');
	$this->assertEquals('/somedir', App::rootUrl());
    }
}
